FROM node:12.18.3

LABEL version="1.0"
LABEL description="This is the base docker image for the Tweet Sentiment Analysis backend API."
LABEL maintainer = ["adnanrafique27@gmail.com"]

WORKDIR /usr/src/app

COPY package*.json ./
RUN ls
RUN npm install --production
COPY . .

EXPOSE 5000

CMD ["node", "backend.js"]



docker build

